# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5bc566ef4656fea11c989e87e75d602a663b62afab9ac670f0d41f1cb3d08389f4214622fe9a2543cdf29a5c35c55e2c0410e2664eb677238ebb262fcceff360

test:
  secret_key_base: c19ad283560cc66c51416339c5cc8fea4b3bca2a62688ced3267c2aec8d5515dacf5e49e7bfcf4a163aaa63cd70ba3d2479a56dab209ae1cfa0fb1108c2ef754

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
